### ISSUE TITLE
Add support for defaultSeverity from tslint.json

### ISSUE THREAD

**Issue by vladimir-djokic** [rich-newman/typescript-analyzer#1]
At some point, **tslint** added support for **defaultSeverity**. **Typescript Analyzer** should be extended to honor this setting (if present in `tslint.json`) and default to it instead of requiring manual user interaction (`Tools -> Options -> Typescript Analyzer`).

My reasoning is to have **tslint** issues shown as errors out-of-the-box (by using `tslint.json` **defaultSeverity**).

**Comment by rich-newman** [comment]
I think this is due to the analyzer using a version of tslint from last year. I didn't try to upgrade the tslint version because the tslint team have changed the syntax of both calling it and the return values, so it isn't as simple as bumping the version numbers and rebuilding.

We'll upgrade it and do a release.

**Comment by rich-newman** [comment]
I've released v1.2, which uses TSLint 5.2.0.  This allows you to set defaultSeverity, and then override it with a severity setting for individual rules.  You have to set 'Show errors' to true in Tools/Options/TypeScript Analyzer to see errors in the Error List though.  There's some more documentation in the updated readme.
