### ISSUE TITLE
TSlint rules with typechecking

### ISSUE THREAD

**Issue by 304NotModified** [rich-newman/typescript-analyzer#11]
Some TSLint [rules Requires Type Info](https://palantir.github.io/tslint/usage/type-checking/)

I'm trying the rule ["completed-docs"](https://palantir.github.io/tslint/rules/completed-docs/) which needs type info (gulp told me, the docs are wrong)

When running with gulp it works, but not in Visual Studio. Is this something that should work?

Thanks again for the fork :)

**Comment by rich-newman** [comment]
Sorry, I haven't implemented that.  As you know, this set of rules needs to understand how to build the code.  Obviously this is straying into compiler rather than linter territory.  It isn't particularly easy to implement in the general case, as we expect VS projects to define the build, and tslint expects a tsconfig.json.

Having said that, VS does support tsconfig.jsons, and I'm guessing you have one of those?  If so I don't think it's that hard to set up a config option for its path and pass it to tslint.

**Comment by 304NotModified** [comment]
Yes I have a tsconfig.json!

Could not live without it, as in the past we had a lot of troubles with the default ones. (Different on each machine)

Would we great if you could add this! Or start with only allowing tsconfig in the root of an project. (Project, not solution).

**Comment by 304NotModified** [comment]
So would we great to pass. Or start with only allowing tsconfig in the root of an project. (Project, not solution).

**Comment by rich-newman** [comment]
Release 1.6 is available, and this has an option to use tsconfig.jsons to locate files and lint rather than just looking directly at the .ts files in VS projects.  The option is Tools/Options/TypeScript Analyzer/Use tsconfig.json files, and by default it's false.

This lets you run the rules that require type info.

There are more details in the [readme](https://github.com/rich-newman/typescript-analyzer/blob/master/README.md), including the rules used for finding tsconfig.jsons if you right-click and run on various items in Solution Explorer.

Let me know what you think.

**Comment by rich-newman** [comment]
Closing as the issue has been addressed I think
