### ISSUE TITLE
Locks typescript files such that child node process must be terminated before saving changes.

### ISSUE THREAD

**Issue by Zarepheth** [rich-newman/typescript-analyzer#12]
If Visual Studio 2017 has been running for a bit, with my solution loaded, making a change to a TypeScript file causes the Typescript Analyzer to run. This may be reasonable - so it can scan and note issues with the modified code; however, it also locks the file such that I cannot save my changes. The "node.exe" process which is running the TypeScript Analyzer must be terminated before I can save my changes.

By disabling the extension and restarting Visual Studio, I can make changes to TypeScript files and save the file after making the changes - and without needing to terminate another process.

**Comment by rich-newman** [comment]
That sounds like tslint itself is hanging, since the node process doesn't do much apart from call it.  Any guesses as to why it might happen - does your project have any strange characteristics?  (E.g. is it large?  use Angular or Codelyzer? custom rules?  hierarchy of tslints?)  Do you by any chance get any errors in the output window (under 'TypeScript Analyzer' in the dropdown: this only appears if there are errors)?

In any case, that behavior isn't great.  For the next release I'll put in an option to disable analysis on saving or opening a file, so it'll only run if you explicitly request it via the context menus if the option is turned on.

**Comment by rich-newman** [comment]
@Zarepheth - Release 1.6 has an option to only run the TypeScript Analyzer if requested (Tools/Options/TypeScript Analyzer/Only run if requested).  This means it **won't** run if you save a file.  You can turn this option on if your node process has hung and save the file without the issues you discuss.

I haven't been able to replicate your issue, other than by forcing the node process to hang.  In general killing the node process in Task Manager then allows the analyzer to recover.  I have also improved the error handling in general in the analyzer: under certain circumstances it could bring VS down completely and that can lead to difficulties with node.

**Comment by Zarepheth** [comment]
After updating the TypeScript Analyzer and re-enabling it in Visual Studio, the problem with locked files is no longer occurring.
I have suspicions that TypeScript Analyzer is contributing to some serious slowdowns in Visual Studio, but at least I can save my changes and continue working. I'll have to look into that option and only call the TypeScript Analyzer when I'm ready for some linting, rather than having it run continuously.

**Comment by Zarepheth** [comment]
It turns out that my builds go much faster if I simply turn off the option to Lint before Building. The Linting after saving my files is not an issue, now that it no longer locks my files.

Thanks for the update!.
