### ISSUE TITLE
Ignore folders during code analysis.

### ISSUE THREAD

**Issue by padmadighe** [rich-newman/typescript-analyzer#14]
Hi,

I've uploaded project structure. We are trying to ignore folder model from analysis but doesn't work.
Ignore Patterns Configuration:
\model\,\node_modules\,\bower_components\,\typings\,\lib\,\vendor\,.min.

![project structure](https://user-images.githubusercontent.com/29100295/28569662-6d779cd0-7158-11e7-9cad-b3485c7ea897.png)

**Comment by rich-newman** [comment]
Those are regular project folders right?  A similar setup works for me with your ignore string.

All the code does is look at the full path of the file on disk (=fullPath) and for each of the comma-separated strings (=ignoreString) does filePath.Contains(ignoreString) and doesn't lint if that's true.  With your example '\model' would be an ignoreString.

One thing the analyzer is not very good at is clearing existing errors if you change this setting: have you tried 'Clear all TypeScript errors' and then running after setting the ignore files?

If that doesn't help then if you can produce a repro project I can take a look.

**Comment by padmadighe** [comment]
Yes its a regular project folder. Also, I manually cleared the errors. 
Attaching sample project (change extension to rar) and configuration
![configuration](https://user-images.githubusercontent.com/29100295/28603881-925ca11c-71e4-11e7-8aff-a5230ccecbd5.png)
[SampleApp.txt](https://github.com/rich-newman/typescript-analyzer/files/1175418/SampleApp.txt)

**Comment by rich-newman** [comment]
I'm assuming you've got 'Use tsconfig.json files' set to true?  The ignore patterns don't yet work with individual files if you're using tsconfig.jsons.  It's buried in my [readme](https://github.com/rich-newman/typescript-analyzer/blob/master/README.md):

'Note that if 'Use tsconfig.json files' is true then the options 'Ignore nested files' and 'Ignore patterns' apply to the discovery of tsconfig.json files, not the files that are linted.'

Which means if your tsconfig.json is on an ignore path it will get ignored, but a file it references won't be.  Since tslint always lints the entire contents of a tsconfig.json the only way to achieve what you want would be to filter the results.  Normally we filter the inputs.  Filtering the results is possible but I wasn't sure if it was necessary.  It's probably possible to workaround this issue, but let me know if you want me to fix it.

There's one other issue that your sample has highlighted.  This is how badly the analyzer deals with large nested node_modules folders when NOT using tsconfig.json.  This is why it's slow if you 'Run TypeScript Analyzer' on your entire solution.  This in spite of the fact that the node_modules folder is being ignored and isn't even in a VS project.  This is bad behavior and I'll fix it for the next release.  I'll raise a separate issue for it.

**Comment by padmadighe** [comment]
We are aware of other issue (NOT using tsconfig.json ) and were supposed to raise issue but currently that is not priority for us.  

I'm still confused with use of tsconfig.json .

1. Typescript Analyzer will ignore node modules  and folders outside of source?

2. its very common use case to ignore certain folders while linting otherwise we need to add tags in code to ignore them. Also, use of custom lint rules is very common. 

3. I don't see filtering output as a workaround because performance will be still bad.

Do you see any other option which can ignore the paths with custom list rules? Meanwhile,  I think we have an option to ignore directories inside tslint.json I will  check on that as well.

Thanks for your quick response as always :-)
Padma

**Comment by rich-newman** [comment]
The performance being bad with big node_modules is a bug: the code is very inefficient.  The bug only happens if you're **not** using tsconfig.json though.  I did it differently for the tsconfig.json implementation.  I will fix the bug. 

As you know, the tsconfig.json is kind of a project file for TypeScript, and usually overrides any Visual Studio projects.  This **is** confusing in Visual Studio, where there are now effectively two TypeScript project types.

If you're using tsconfig.json files then all the analyzer does is pass those to tslint.  This restricts how much control we have outside of tslint.  However, you can configure your tsconfig.json to include/exclude files and tslint will take account of that. 

Normally you'd exclude folders from compilation in a tsconfig.json by using an 'exclude' section, see below.  Note that we have to specifically exclude 'node_modules' or tslint will lint it, even though it doesn't do that if there's no exclude section.

```json
{
  "compileOnSave": true,
  "compilerOptions": {
    "outDir": "./dist/out-tsc",
    "baseUrl": "src",
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "es5",
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2016",
      "dom"
    ]
  },
  "exclude": [
    "wwwroot",
    "dist",
    "node_modules",
    "**/model/*"
  ]
}
```

The tsconfig.json above works with your project.  It's reasonably quick and the analyzer gives no linting errors.  However, there's a small problem.

The 'exclude' excludes those files both from linting and compilation/transpilation.  This is fine for node_modules and probably dist.  You don't want those files compiled.  However for the stuff in model you may actually want compilation to JavaScript.

My original idea was that anything that needs to get compiled should probably be linted, so you wouldn't need additional excludes specifically for linting.  It looks like that may not be the case?  One workaround might be to use two tsconfigs, one for linting and one for compilation, but that's getting messy.

So in answer to your specific questions:

1.  With tsconfig.json the analyzer hands the tsconfig.json to tslint and displays the results.  Anything included in the tsconfig will be linted, anything excluded won't be, regardless of whether it's in a Visual Studio project or not.  node_modules is, confusingly, excluded by default **unless** you have an 'exclude' section, when it needs to be in there.

2. As mentioned above if 
* you want to use tsconfigs and 
* you have stuff that needs to be compiled in that tsconfig but you don't want linted 

then at the moment the analyzer doesn't support that.  It isn't possible to stop the linting, but we could filter the results.

3. I don't think with your project that the performance will be bad if I fix the bug.

OK that was a very long answer, I hope I haven't confused you even more.

**Comment by padmadighe** [comment]
Thanks for the detailed information. :-)

**Comment by rich-newman** [comment]
I've done a release that fixes the bug.  It also fixes another one that I found that stops the analyzer showing errors when there are a lot of them that aren't in a project.

You should find that the analyzer works a bit better with your project now.  It will even just about lint if you include node_modules by mistake: it's taking about 8 seconds to show about 3,000 errors on my machine if I do that.
