### ISSUE TITLE
System.Exception: Node set up not valid on sync call, TSLint not run

### ISSUE THREAD

**Issue by jitterbox** [rich-newman/typescript-analyzer#22]
I looked at source code to try to determine the cause of this error, since I'm still getting the expected TS errors when I run it on build.  Is this significant, and is there an easy resolution?

**Comment by rich-newman** [comment]
I would say that the most likely explanation for this is if something is clearing out your temp folder whilst you are running Visual Studio.  

The TypeScript Analyzer uses a node webserver to run tslint.  It creates a folder with the executables for this in temp on the fly. The folder is %temp%\TypeScriptAnalyzer1.12.  On every run the Analyzer checks if this folder is correctly set-up and if it's not it recreates it.    

There's one exception to the Analyzer recreating the folder on every run: running synchronously on a build.  Normally the Analyzer runs async, meaning the UI thread is freed up whilst the linting takes place.  However, if we need to stop a build if there are errors the only way to do this is to do the linting in a blocking sync callback from the build process, on the UI thread. 

Anyway, as you can see in my comments, I didn't want the code that tries to recreate the TypeScriptAnalyzer1.2 folder running on a synchoronous call.  It's unzipping some large files, and is expensive, and would block the UI thread for a while.  Also it shouldn't be necessary: the folder is created when Visual Studio is started.

All of which is a long way of saying that 'node set up not valid' means there's probably something wrong with the %temp%\TypeScriptAnalyzer1.2 folder, possibly it's been deleted.  If what I'm suggesting is correct it will just fail for the build and then reinstall correctly on the next async call, which happens when you open a file in the editor or save one, or run TypeScript Analyzer from the context menu. 

So what I suggest is: confirm the folder exists (just type %temp% into the address bar in File Explorer and look for TypeScriptAnalyzer1.12), and then next time you get the error immediately look to see if it's still there.  If not try to work out why it disappeared.  Nothing in the Analyzer deletes it ever.  I really thought it wouldn't be a problem but I *can* fix it by reinstalling on a sync call if that's what's happening.

**Comment by rich-newman** [comment]
@jitterbox Did you resolve this?

**Comment by jitterbox** [comment]
Thanks for checking - I've kept the extension up-to-date and haven't seen the error again since, I don't believe.
On a separate note, though, just last week I _did_ run into the sort of opposite error, which was corrected by _deleting_ the temp folder per the Q&A section on the VS Marketplace page:
"System.UnauthorizedAccessException: Access to the path 'node.exe' is denied."
