### ISSUE TITLE
Separate HTML templates not being analyzed using Codelyzer v4.1.0

### ISSUE THREAD

**Issue by k-vekos** [rich-newman/typescript-analyzer#26]
Currently in my project if I run `node node_modules/tslint/bin/tslint -p "./tsconfig.json" -o "results.txt" -t "prose"` in the output file `results.txt` I can see findings occurring in separate HTML template files referenced by Angular components (using `templateUrl`)

However I am not seeing any HTML file findings in my Problems list in Visual Studio when I am using TypeScript Analyzer.

Here are my extension settings:
![image](https://user-images.githubusercontent.com/23462254/35927862-bce9e98a-0bf9-11e8-8721-36966f3f33a6.png)

tsconfig.json:
```
{
  "compilerOptions": {
    "module": "es2015",
    "moduleResolution": "node",
    "target": "es5",
    "sourceMap": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "skipDefaultLibCheck": true,
    "skipLibCheck": true, // Workaround for https://github.com/angular/angular/issues/17863. Remove this if you upgrade to a fixed version of Angular.
    "strict": true,
    "lib": [ "es6", "dom" ],
    "types": [ "webpack-env" ]
  },
  "exclude": [ "bin", "node_modules" ],
  "atom": { "rewriteTsconfig": false }
}
```

tslint.json:
```
{
  "extends": [ "tslint-angular" ], // (See: https://github.com/mgechev/tslint-angular)
  "format": "msbuild",
  "typeCheck": true,
  "fix": false,
  "project": "./tsconfig.json",
  "rules": {
    "directive-selector": [ true, "attribute", "foo", "camelCase" ],
    "component-selector": [ true, "element", "foo", "kebab-case" ],
    "max-classes-per-file": false,
    "i18n": [ true, "check-text" ],
    "quotemark": false,
    "prefer-const": false,
    "no-trailing-whitespace": false,
    "max-line-length": false,
    "curly": false
  }
}
```

**Comment by rich-newman** [comment]
I don't think the problem is the templates.  The Analyzer deals with linting errors in them fine.  See below, which is output from the latest version of the TypeScript Analyzer.  It shows errors in both css and html files in a standard Angular CLI project, created with 'ng new foo'.  I just added an unused style in app.component.css and a load of *ngIf statements in app.component.html.  I also made sure the appropriate rules were in tslint.json in the project of course.

![image](https://user-images.githubusercontent.com/17277125/39264717-7aca11e6-48bd-11e8-8493-a6ceae645027.png)

I actually suspect the codelyzer rules aren't working for you at all.  You have 'Use local ng lint' set to False, and as I say in the readme if you do that you have to be running the same versions of TypeScript and tslint locally as your version of the Analyzer is using (currently ts 2.8.1 and tslint 5.9.1).  This is what I set up for the screenshot above.

There's an easier way though: just set 'Use local ng lint' to True, assuming this is a regular Angular project and 'ng lint' works from the command line.  The Analyzer will run it as if from the command line and show the results.

Let me know if none of that works.
