### ISSUE TITLE
`"extends"` configuration property doesn't take any effect.

### ISSUE THREAD

**Issue by kapral** [rich-newman/typescript-analyzer#3]
When I set '"extends":' to `"tslint:recommended"` or anything else in `tslint.json` the specified rules are not inherited by the analyzer. When I run [grunt-tslint](https://github.com/palantir/grunt-tslint) with the same config file the rules are inherited.

**Comment by rich-newman** [comment]
I think this is due to the analyzer using a version of tslint from last year. I didn't try to upgrade the tslint version because the tslint team have changed the syntax of both calling it and the return values, so it isn't as simple as bumping the version numbers and rebuilding.

We'll upgrade it and do a release.

**Comment by rich-newman** [comment]
I've released v1.2, which uses TSLint 5.2.0.  You can now use "extends" with "tslint:recommended".
