### ISSUE TITLE
Running tslint on .js files

### ISSUE THREAD

**Issue by visualbam** [rich-newman/typescript-analyzer#34]
**TSlint** can be used with **.js** files. **typescript-analyzer** doesn't appear as an option when selecting a **.js** file. Is this expected?

**Comment by rich-newman** [comment]
It's expected in the sense that it's currently coded that way.  The code it's based on used eslint for .js files with no way to tell it to use tslint.  We've never upgraded to allow tslint for .js files.

Of course Visual Studio 2017 by default lints .js files with eslint via its 'Web Code Analysis' options.  So having both linters working with .js files might give some potential for confusion.  The separate 'jsrules' section in a tslint.json helps with this though, since it can just be empty by default.

I can see it might be useful to be able to use tslint for everything, and I don't think it's a particularly big change.  

Would it be useful to you?

**Comment by visualbam** [comment]
It would be! Although using tslint and eslint for linting works fine, eslint doesn't have the capability of breaking msbuild where as tslint does.

The solution I'm trying to solve is that I don't want my project to build if there are linting errors. I tested this extension with .ts files and it seemed to work as expected. I'm making an assumption that it would work the same with .js files.

**Comment by rich-newman** [comment]
OK we'll have a look at adding it in

**Comment by rich-newman** [comment]
This enhancement has just been released as part of version 1.17.  There's some information in the readme on how to use it: it has to be enabled in Tools/Options as well as adding a jsRules section to tslint.json.
