### ISSUE TITLE
Doesn't compile when introducing local tslint.json 

### ISSUE THREAD

**Issue by spikeeedge** [rich-newman/typescript-analyzer#38]
Hi,
I'm trying to introduce this tool among my team mates for quality assurance and to do so, I introduce the local tslint.json file for common rules across the team.

adding this file, the analyzer stops working. In the output window it throws following error.

![image](https://user-images.githubusercontent.com/11339925/55117012-37a42200-5139-11e9-8361-0b8767e04b01.png)

If I run the "Typescript Anlayzer" on a perticular folder then it compiles successfully.

tslint.json
{
  "defaultSeverity": "warning",
  "extends": "tslint:recommended",
  "rules": {    
    "no-consecutive-blank-lines": true
  }
}

TSLint Settings
![image](https://user-images.githubusercontent.com/11339925/55117087-776b0980-5139-11e9-8c0d-da1ff2573b5d.png)

I'm using VS2017 with C# project

**Comment by rich-newman** [comment]
@spikeeedge Your tslint.json and settings work fine for me in my test projects.  It must be something to do with your project structure and rules I think.  

One thing to try is to turn on Ignore nested files (set it to True) as we've had problems with that in the past, although I think they should all be fixed.  

You could also try running tslint from the command line on your files, to see if it's an Analyzer problem or a tslint rule problem.  If it's a tslint rule problem that may give you better error messages too.  There are instructions on the [tslint site](https://palantir.github.io/tslint/) on how to do that.

Otherwise you should be able to narrow down which part of your project has the problem by using Solution Explorer to Run TypeScript Analyzer at various levels and on various files and seeing where it fails. 
 You imply it doesn't fail on most individual folders, which suggests there's probably one somewhere where it does fail.  If you can provide me with a test folder or project that fails I can debug, or can help you to.

**Comment by spikeeedge** [comment]
Thank @rich-newman for the reply

I tried the different test cases you mentioned earlier. I found when the following option is turned On under VS Options, TsLint doesn't analyse the files.

![image](https://user-images.githubusercontent.com/11339925/55603665-492d9f80-57b3-11e9-8be7-9a4469e381f2.png)

turning this option off, it works as expected. 

I have created the test project to replicate this issue. 

[ReplicateIssue](https://github.com/spikeeedge/TSLintAnalyserReplicateIssue)

not sure what I have missed!

**Comment by rich-newman** [comment]
The Analyzer is working with that project as far as I can see - the reason there's no linting if you ask it to use tsconfig.json files is that there are no tsconfig.json files.  Am I missing something?

**Comment by spikeeedge** [comment]
I missed to place tsconfig.json file into the project. my bad :( after adding this file and changing settings, the analyser work as expected. 

not sure why it's not working in my work project though tsconfig.json file is present! I have to dig a bit more to find the cause of this issue. but because now I have working scenario, I believe It would help.

thanks all your support @rich-newman the tool is awsome
