### ISSUE TITLE
Visual Studio 2017-Pre-build Event/Post-build Event 

### ISSUE THREAD

**Issue by padmadighe** [rich-newman/typescript-analyzer#5]
Is there any way to use "TypeScript Analyzer" extension with Pre/Post build events?

**Comment by rich-newman** [comment]
Not at the moment.  What do you want it to do?

**Comment by padmadighe** [comment]
We are trying to integrate type script style check  with build.

Other approaches
1. We have also tried npm task runner extension to run "ng lint" script . Errors are logged in the task explorer but we can not navigate to the error location.

2 As workaround, we have written custom task runner that runs required scripts during post build event and logs error to the output window. Now, errors can be navigated but the issue is we are not able to get these errors in error indow.

**Comment by rich-newman** [comment]
So is the requirement just that the analyzer should run on a build? Or do you need more than that?

**Comment by padmadighe** [comment]
Requirement is to run  analyzer on post build event and build should fail for lint  errors. Also, user should be able to navigate/supress  error from error window.

**Comment by rich-newman** [comment]
I've released a version (1.4) that will let you run the analyzer on a build, and will stop the build if there are errors in the Error List window as a result of the build.

It isn't quite what you asked for: I didn't think a pre/post build event was appropriate, and the linter runs before the build and stops it if there are errors.

If you go to Tools/Options/TypeScript Analyzer and set 'Run on build' to true then the linter will run before any build.

It will only stop a build if there are actual errors (red circles) in the Error List window from the build.  By default everything the linter raises is a warning, so if you want this to happen you need to set 'Show errors' to true as well.

Both of these flags are set to false by default.  The reason is I don't think most people will want their builds failing because of trailing whitespace etc, although it may be a useful option to have.

Let me know if that's useful.

**Comment by padmadighe** [comment]
That's awesome :-) I'll try it out tomorrow and let you know.
Thank you so much  :-)

**Comment by padmadighe** [comment]
Hi, 

Please see attached configuration where show error is on.
![confgi](https://user-images.githubusercontent.com/29100295/26862213-0b4a65b8-4b67-11e7-8e0e-f8952164fa0a.png)

I've added whitespace to the code to get below warning but build is completed without any problem
![warning](https://user-images.githubusercontent.com/29100295/26862199-e95d0168-4b66-11e7-9d69-bc294758fedd.png).

Also, on multiple builds I'm getting 'access denied warning'
1>G:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Microsoft\VisualStudio\v15.0\TypeScript\Microsoft.TypeScript.targets(223,5): warning : Failed to write compiler log to 'obj\Debug\netcoreapp1.1\TypeScriptCompilerOutput.txt. Exception: 'The process cannot access the file 'E:\KTA\Agility\Code\Client\Designer\Designer\obj\Debug\netcoreapp1.1\TypeScriptCompilerOutput.txt' because it is being used by another process.'

Did I miss any configuration?

Thanks
Padma

**Comment by rich-newman** [comment]
You need to get it to show an error in the Error List (red), not a warning (yellow).  It needs to be a tslint error, not a tslint warning, and then have the config set up as you have. 

I suggest trying this:

- Start a blank TypeScript node console app if you have it installed (New project/Templates/TypeScript/Blank Node.js Console Application)
- Reset the TypeScript Analyzer (Tools/TypeScript Analyzer/Reset TypeScript Analyzer Settings). This restores the default tslint.json to the one shipped with the extension
- Set the Tools/Options settings as shown above
- Run the analyzer: you should get three red errors in the Error List
- Do a build - it should say 'Build failed because of TSLint Errors' in the status bar

I don't think your multiple build error is caused by the analyzer (it might be): can you try disabling the analyzer in Tools/Extensions and Updates and see if you still get it?

**Comment by padmadighe** [comment]
Ok rich but the requirement is to fail build even for warnings also :( . Is there anyway acheive that?

**Comment by rich-newman** [comment]
You have a lot of flexibility with configuration through tslint.json.  You can configure individual rules to be errors or warnings, or you can change the default severity level so that they all (if not overridden) are errors or warnings, or even extend one tslint.json where they are warnings with another one that overrides and makes them errors.

My feeling was that a 'treat warnings as errors' flag would just add confusion to what is already pretty confusing behavior.  Is there a reason you need it and the tslint stuff isn't flexible enough?

**Comment by padmadighe** [comment]
For all projects in VS we set treat warnings as error. However, I think it should be ok for us to set warning as error in tslint configuration file. 

 Also, regarding the warning related to access denied in the output window,  do we need to provide  any access to the folder?

By the way, tool is now very usable for us, thanks for providing fix so quickly.

**Comment by rich-newman** [comment]
Your access denied error sounds like the analyzer is locking something it shoudn't be and conflicting with the main build: I'm not seeing this though.  Can you provide me with a simple repro?

**Comment by padmadighe** [comment]
If I change , severity to error  then 'ng lint' command  throws error for whitespace so this option is  ok for us. However, how to change default  location of  tslint.json to search in project folder (as per tool's documentation, we can change it)? 

I'll recreate 'access denied error' with sample project and will send.

**Comment by rich-newman** [comment]
If you just put a tslint.json in the project folder and then right-click the project in Solution Explorer and run then it will use that tslint.json.  I've had a closer look at the logic for this though: I didn't write this bit and wasn't sure how it works.  It isn't perfect.  The full logic is below.

The analyzer looks in the folder of the first file it is linting for a file called tslint.json, and then if it doesn't find one it walks up the folder tree trying to find one in any parent folder.  If it doesn't find one anywhere in any of that it uses the one installed with the analyzer, which is in Environment.SpecialFolder.UserProfile: this is something like c:\Users\{username}\tslint.json.  

It then uses that file for every file it lints for that run of the analyzer.  This is because tslint itself only supports one config file for a run I think.

This logic isn't so great if you want different configs at different levels in the same solution, since running it at solution level will always use the first one it finds for everything I think.  You'd have to actually run it at the right level.

**Comment by padmadighe** [comment]
Ok now I can get errors using type analyzer and also can not replicate access denied error :-)

last question, is there any way we can check if this extension is installed before starting build or install extension on opening solution?  
I can write custom code if required.

**Comment by padmadighe** [comment]
Hi, after internal discussion with team, we are ok with the provided solution. Thanks for all your help :-)
